# Generated by Django 6.0.4 on 2026-04-21 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.RemoveField(
            model_name='room',
            name='image_url',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(default='Queen Bed', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='has_air_conditioning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_hairdryer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_minibar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_parking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_room_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_safe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_spa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_tv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='room',
            name='image3',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='room',
            name='image4',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='room',
            name='main_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.IntegerField(default=30, help_text='Room size in square meters'),
        ),
        migrations.AddField(
            model_name='room',
            name='view_type',
            field=models.CharField(choices=[('city', 'City View'), ('ocean', 'Ocean View'), ('mountain', 'Mountain View'), ('garden', 'Garden View'), ('pool', 'Pool View')], default='city', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard Room'), ('deluxe', 'Deluxe Room'), ('premier', 'Premier Room'), ('suite', 'Suite'), ('family', 'Family Room'), ('presidential', 'Presidential Suite')], default='standard', max_length=20),
        ),
    ]
