# Generated by Django 4.2.28 on 2026-04-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_reservation_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_beach_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_jacuzzi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_kids_club',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_lagoon_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_tennis_court',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_water_park',
            field=models.BooleanField(default=False),
        ),
    ]
