# Generated by Django 4.2.28 on 2026-04-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_has_beach_access_room_has_jacuzzi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResortAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏝️', max_length=10)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_beach_access',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_jacuzzi',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_kids_club',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_lagoon_access',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_tennis_court',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_water_park',
        ),
    ]
