# Generated by Django 6.0.2 on 2026-05-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resortamenity_remove_room_has_beach_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='main_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
